### ISSUE TITLE
Tracking Files

### ISSUE THREAD

**Issue by rstoneback** [rstoneback/pysat#48]
To support future missions and pysat's use as a science operations center, basic functionality has been added to the files class to check if there are new files present. The idea is that pysat could run in the background, polling directories, and process files as they appear.

The is support for storing and loading the files in a directory, along with a basic routine to get a list of new files. Files are identified by name only.
Need support for :
  - marking files as old after being processed
  - marking files as new, so they can be processed again
  - better identification of file, rather than just a filename

**Comment by jklenzing** [comment]
- identify gaps in data for users
- track file creation dates
- track version and revision numbers

**Comment by rstoneback** [comment]
The current implementation identifies files as 'new' by comparing the current list of files against the archived list. The disadvantage of this technique is files can age out of 'new' without the user actually interacting with the file. Since this feature was originally intended to assist with mission data processing it feels like it should be more robust. 


Current:
 - Any files in current file list but not archive are considered 'new'. Auto fill, auto removal.
 
Alternate:
 - Make the whole thing manual. Manual fill, manual removal.

Leading towards:
 - Make 'new' expand as files are added, but only remove a file from 'new' as directed by the user. Auto fill, manual removal.

**Comment by rstoneback** [comment]
Topics to be completed:

 - [ ] Add support for getting file attributes
 - [ ] Add file attribute storage to the current file list
 - [ ] Incorporate attribute use when determining what is new
